// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Pokemon struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Category    string   `json:"Category"`
	Type        []string `json:"Type"`
	Abilities   []string `json:"Abilities"`
}

type IDToModify struct {
	ID string `json:"id"`
}

type NewPokemon struct {
	ID          *string  `json:"id,omitempty"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Category    string   `json:"Category"`
	Type        []string `json:"Type"`
	Abilities   []string `json:"Abilities"`
}
